# Generated by Django 5.0 on 2024-01-12 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('no_of_people', models.CharField(max_length=50)),
                ('hotel', models.ImageField(blank=True, null=True, upload_to='package_photos/')),
                ('destination', models.ImageField(blank=True, null=True, upload_to='package_photos/')),
                ('activity', models.ImageField(blank=True, null=True, upload_to='package_photos/')),
                ('attraction', models.ImageField(blank=True, null=True, upload_to='package_photos/')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
