# Generated by Django 5.0 on 2024-01-12 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0002_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('food', models.ImageField(blank=True, null=True, upload_to='blog_photos/')),
                ('hotel', models.ImageField(blank=True, null=True, upload_to='blog_photos/')),
                ('travelling', models.ImageField(blank=True, null=True, upload_to='blog_photos/')),
                ('activity', models.ImageField(blank=True, null=True, upload_to='blog_photos/')),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_operations.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
