# Generated by Django 4.1.13 on 2024-01-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0003_alter_package_rating_blogs_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('review', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
