# Generated by Django 5.0.3 on 2024-07-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0006_packageselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='desc_food',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='hotel_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='hotel_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='hotel_rating',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='hotel_title',
            field=models.FileField(null=True, upload_to='hotel image'),
        ),
        migrations.AddField(
            model_name='package',
            name='imgnon_veg',
            field=models.FileField(null=True, upload_to='Non veg food image'),
        ),
        migrations.AddField(
            model_name='package',
            name='imgveg',
            field=models.FileField(null=True, upload_to='veg food image'),
        ),
        migrations.AddField(
            model_name='package',
            name='non_veg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='veg',
            field=models.TextField(null=True),
        ),
    ]
