# Generated by Django 5.0.3 on 2024-07-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0007_package_desc_food_package_hotel_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageselection',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='packageselection',
            name='no_of_people',
            field=models.IntegerField(null=True),
        ),
    ]
