# Generated by Django 5.0.3 on 2024-07-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0009_userpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='no_of_people',
        ),
    ]
