# Generated by Django 5.0.3 on 2024-07-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0010_remove_package_no_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='hotel_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
