# Generated by Django 5.0.3 on 2024-07-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0011_alter_package_hotel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='hotel_rating',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
