# Generated by Django 5.0.3 on 2024-07-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespackage', '0004_remove_trip_no_of_peoples'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='desc_food',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel_img',
            field=models.FileField(null=True, upload_to='hotel image'),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel_rating',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='imgnon_veg',
            field=models.FileField(null=True, upload_to='Non veg food image'),
        ),
        migrations.AddField(
            model_name='trip',
            name='imgveg',
            field=models.FileField(null=True, upload_to='veg food image'),
        ),
        migrations.AddField(
            model_name='trip',
            name='non_veg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='veg',
            field=models.TextField(null=True),
        ),
    ]
