# Generated by Django 5.0.1 on 2024-08-03 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salespackage', '0006_remove_trip_desc_food_remove_trip_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='no_of_peoples',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
